/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;


import konfigurasi.Koneksi;
import java.sql.*;
import javax.swing.JButton;
import javax.swing.JOptionPane;
/**
 *
 * @author Septa
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        label_regis = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        user_logo = new javax.swing.JLabel();
        pw_logo = new javax.swing.JLabel();
        form_user = new javax.swing.JTextField();
        label_password = new javax.swing.JLabel();
        button_daftar = new javax.swing.JButton();
        JButton2 = new javax.swing.JButton();
        form_pw = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/smp62logo - Copy.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        label_regis.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_regis.setText("Registrasi akun");
        getContentPane().add(label_regis, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        label_username.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        label_username.setForeground(new java.awt.Color(153, 153, 153));
        label_username.setText("Username");
        getContentPane().add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        user_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        getContentPane().add(user_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        pw_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        getContentPane().add(pw_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        form_user.setBackground(new java.awt.Color(204, 204, 255));
        form_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        form_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_userActionPerformed(evt);
            }
        });
        getContentPane().add(form_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 210, 30));

        label_password.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        label_password.setForeground(new java.awt.Color(153, 153, 153));
        label_password.setText("Password");
        getContentPane().add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        button_daftar.setBackground(new java.awt.Color(102, 102, 255));
        button_daftar.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        button_daftar.setText("Daftar");
        button_daftar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.blue));
        button_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_daftarActionPerformed(evt);
            }
        });
        getContentPane().add(button_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 80, -1));

        JButton2.setBackground(new java.awt.Color(255, 0, 102));
        JButton2.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        JButton2.setText("Kembali");
        JButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.pink));
        JButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(JButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 80, -1));

        form_pw.setBackground(new java.awt.Color(204, 204, 255));
        form_pw.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        form_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_pwActionPerformed(evt);
            }
        });
        getContentPane().add(form_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 210, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public register(JButton JButton2) {
        this.JButton2 = JButton2;
        
    }
    
    private void form_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_userActionPerformed

    private void button_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_daftarActionPerformed
        // TODO add your handling code here:
       try {
           Connection conn = Koneksi.getConnection();
            String sql = "INSERT INTO akun VALUES ('"+form_user.getText()+"','"+form_pw.getText()+"')";
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil terdaftar, kembali ke login!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_button_daftarActionPerformed

    private void JButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton2ActionPerformed
        // TODO add your handling code here:
        login login=new login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JButton2ActionPerformed

    private void form_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_pwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton2;
    private javax.swing.JLabel background;
    private javax.swing.JButton button_daftar;
    private javax.swing.JTextField form_pw;
    private javax.swing.JTextField form_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_regis;
    private javax.swing.JLabel label_username;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel pw_logo;
    private javax.swing.JLabel user_logo;
    // End of variables declaration//GEN-END:variables
}
